[platformio]
build_dir = C:/pio-build/cybershot-cam

[env:esp32-s3-cam]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
board_upload.flash_size = 16MB
build_flags =
    -DBOARD_HAS_PSRAM
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_rts = 0
monitor_dtr = 0
lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
    bitbank2/JPEGDEC
